apiVersion: v1
kind: Service
metadata:
  name: {{ include "filerun.fullname" . }}
  labels:
    {{- include "filerun.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component:  {{ .Chart.Name }}
